import io
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from typing import Dict, Any, List
import re
from datetime import datetime


# Indian flag colors
SAFFRON = RGBColor(0xFF, 0x99, 0x33)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GREEN = RGBColor(0x13, 0x88, 0x08)
NAVY = RGBColor(0x00, 0x00, 0x80)
DARK = RGBColor(0x1A, 0x1A, 0x2E)


def _add_heading(doc: Document, text: str, level: int = 1):
    heading = doc.add_heading(text, level=level)
    run = heading.runs[0] if heading.runs else heading.add_run(text)
    if level == 1:
        run.font.color.rgb = SAFFRON
        run.font.size = Pt(16)
    elif level == 2:
        run.font.color.rgb = NAVY
        run.font.size = Pt(13)
    else:
        run.font.color.rgb = DARK
        run.font.size = Pt(11)
    return heading


def _add_colored_bar(doc: Document):
    """Add saffron-white-green tricolor bar."""
    table = doc.add_table(rows=1, cols=3)
    table.style = 'Table Grid'
    colors = [SAFFRON, WHITE, GREEN]
    for i, cell in enumerate(table.rows[0].cells):
        cell.width = Inches(2.1)
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        shd = OxmlElement('w:shd')
        rgb = colors[i]
        hex_color = f"{rgb.rgb[0]:02X}{rgb.rgb[1]:02X}{rgb.rgb[2]:02X}"
        shd.set(qn('w:fill'), hex_color)
        shd.set(qn('w:val'), 'clear')
        tcPr.append(shd)
        cell.paragraphs[0].add_run(" ")
    doc.add_paragraph()


def generate_legal_brief(
    workspace_name: str,
    case_facts: str,
    prosecution_args: str,
    defense_args: str,
    verdict_analysis: str,
    citations: List[Dict],
    probability: Dict = None,
) -> bytes:
    """Generate a professional Indian legal brief as DOCX."""
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(3)
        section.right_margin = Cm(2)

    # Header bar
    _add_colored_bar(doc)

    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("LEGAL ANALYSIS BRIEF")
    run.bold = True
    run.font.size = Pt(20)
    run.font.color.rgb = DARK

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run(f"Case: {workspace_name}")
    sub_run.font.size = Pt(13)
    sub_run.font.color.rgb = NAVY
    sub_run.bold = True

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.add_run(f"Generated by LexAI | {datetime.now().strftime('%d %B %Y')}")

    doc.add_paragraph()
    _add_colored_bar(doc)
    doc.add_paragraph()

    # Disclaimer
    disc = doc.add_paragraph()
    disc_run = disc.add_run(
        "⚠ DISCLAIMER: This document is generated by an AI system for informational purposes only "
        "and does not constitute legal advice. Please consult a licensed advocate before taking any legal action."
    )
    disc_run.font.size = Pt(9)
    disc_run.font.color.rgb = RGBColor(0x99, 0x00, 0x00)
    disc_run.italic = True

    doc.add_page_break()

    # 1. Case Facts
    _add_heading(doc, "1. CASE FACTS & BACKGROUND", 1)
    doc.add_paragraph(case_facts or "No case facts provided.")
    doc.add_paragraph()

    # 2. Verdict Probability
    if probability:
        _add_heading(doc, "2. VERDICT PROBABILITY ANALYSIS", 1)
        table = doc.add_table(rows=4, cols=2)
        table.style = 'Light Shading Accent 1'
        headers = [("Outcome", "Probability"), ("Guilty", f"{probability.get('guilty', 0):.1f}%"),
                   ("Not Guilty", f"{probability.get('not_guilty', 0):.1f}%"),
                   ("Partial Relief", f"{probability.get('partial_relief', 0):.1f}%")]
        for i, (col1, col2) in enumerate(headers):
            row = table.rows[i]
            row.cells[0].text = col1
            row.cells[1].text = col2
        doc.add_paragraph()

    # 3. Prosecution Arguments
    _add_heading(doc, "3. PROSECUTION ARGUMENTS", 1)
    doc.add_paragraph(prosecution_args or "No prosecution arguments provided.")
    doc.add_paragraph()

    # 4. Defense Arguments
    _add_heading(doc, "4. DEFENSE ARGUMENTS & COUNTER-ARGUMENTS", 1)
    doc.add_paragraph(defense_args or "No defense arguments provided.")
    doc.add_paragraph()

    # 5. Legal Analysis
    if verdict_analysis:
        _add_heading(doc, "5. LEGAL ANALYSIS & RECOMMENDATIONS", 1)
        doc.add_paragraph(verdict_analysis)
        doc.add_paragraph()

    # 6. Citations
    if citations:
        _add_heading(doc, "6. LEGAL CITATIONS & PRECEDENTS", 1)
        for i, cite in enumerate(citations, 1):
            p = doc.add_paragraph(style='List Number')
            run = p.add_run(cite.get("title", "Unknown"))
            run.bold = True
            run.font.color.rgb = NAVY
            p.add_run(f"\n   Court: {cite.get('court', 'N/A')}")
            p.add_run(f"\n   Date: {cite.get('date', 'N/A')}")
            if cite.get("url"):
                p.add_run(f"\n   URL: {cite.get('url')}")
            p.add_run(f"\n   Citation: {cite.get('citation', '')}")

    # Footer bar
    doc.add_page_break()
    _add_colored_bar(doc)
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_p.add_run("Generated by LexAI — Indian Legal AI Assistant | For informational purposes only")

    # Save to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()
